name: GitHub Profile Views Counter CI
on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:
jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.INSIGHTS_TOKEN }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 18
      - uses: formidablae/github-profile-views-counter-action@3.2.0
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
      - name: Commit & Push
        run: |
          git config user.name "View Counter"
          git config --global user.email "26270646+MuhammadSaadSiddique@users.noreply.github.com"
          git add -A .
          git commit -m "Add view Counter"
          git push
